FROM openjdk:8
MAINTAINER adarshkumarsingh83@gmail.com
ADD target/springboot-jpa-mysql-docker.jar springboot-jpa-mysql-docker.jar
EXPOSE 9090
ENTRYPOINT ["java","-jar","springboot-jpa-mysql-docker.jar"]