version: "3.2"
services:
  espark-mysql:
    container_name: espark-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=espark
      - MYSQL_USER=espark-root
      - MYSQL_PASSWORD=espark-root
    ports:
      - 3306:3306
    volumes:
      - /data/espark-mysql
    networks:
      - spring-ms

  springboot-jpa-mysql-docker:
    depends_on:
      - espark-mysql
    image: springboot-jpa-mysql-docker
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure:5
    volumes:
      - /data/springboot-jpa-mysql-docker
    links:
      - espark-mysql
    ports:
      - 9090:9090
    environment:
      - DATABASE_HOST=espark-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=espark
      - DATABASE_PORT=3306
    networks:
      - spring-ms
networks:
  spring-ms:
